apiVersion: v1
kind: Pod
metadata:
  name: nodeappenv
spec:
  containers:
  - image: ongolenavee/logarguments:latest
    name: nodeappenv-manual
    env:
    - name: INTERVAL
      value: "30"
    ports:
    - containerPort: 80
      protocol: TCP

