apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-args-from-configmap
spec:
  containers:
  - image: ongolenavee/logarguments:latest
    name: nodeapp-manual
    env:
    - name: INTERVAL
      valueFrom: 
        configMapKeyRef:
          name: nodeapp-config
          key: sleep-interval
          optional : true
    args: ["$(INTERVAL)"]
