apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodeapp-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
        - key: app
          operator: In
          values:
            - nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: apigee-node-express-app-rc
        image: ongolenavee/apigee-node-express-app:latest
