apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeapp-rc
spec:
  replicas: 3
  selector:
    app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: apigee-node-express-app-rc
        image: ongolenavee/apigee-node-express-app:latest
        ports:
        - containerPort: 8085
        livenessProbe:
            httpGet:
              path: healthcheck
              port: 8085
            initialDelaySeconds: 15
