apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-manual-lables
  labels:
    creation_method: manual
    env: development
spec:
  containers:
  - image: ongolenavee/apigee-node-express-app:latest
    name: apigee-node-express-app-manual-label
    ports:
    - containerPort: 8085
      protocol: TCP